/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_jnidemo_JniUtil */

#ifndef _Included_com_lenovo_jnidemo_JniUtil
#define _Included_com_lenovo_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_jnidemo_JniUtil
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_jnidemo_JniUtil_getJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_lenovo_jnidemo_JniUtil
 * Method:    getJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lenovo_jnidemo_JniUtil_getJniAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
