/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_jnidemo_JniUtil */

#ifndef _Included_com_lenovo_jnidemo_JniUtil
#define _Included_com_lenovo_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_jnidemo_JniUtil
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_jnidemo_JniUtil_getJniString
        (JNIEnv *env, jclass cls){
    char *str = "this is from c file in jni.";
    return (*env)->NewStringUTF(env,str);
}

/*
 * Class:     com_lenovo_jnidemo_JniUtil
 * Method:    getJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lenovo_jnidemo_JniUtil_getJniAdd
        (JNIEnv *env, jclass cls, jint a, jint b){
    return a+b;
}

#ifdef __cplusplus
}
#endif
#endif
